version: '3.7'
services:
  db:
    build:
      context: .
      dockerfile: dockerfiles/db/Dockerfile
    container_name: rrrp-db-cont
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    image: rrrp-db-img
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: dockerfiles/web/Dockerfile
    container_name: rrrp-web-cont
    depends_on:
      - db
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DB_HOST
      - DB_PORT
      - DB_DEV_NAME
      - DB_TEST_NAME
      - DB_PROD_NAME
      - ADMIN_STAFF_HOST_NAME
      - CUSTOMER_HOST_NAME
      - RAILS_SERVE_STATIC_FILES
      - RUBYOPT
      - TZ
    image: rrrp-web-img
    ports:
      - 3000:3000
    tty: true
    volumes:
      - .:/proj-cont
      - ./vendor/bundle:/usr/local/bundle
      - ./node_modules:/proj-cont/node_modules
      - ./tmp/sockets:/proj-cont/tmp/sockets
      - ./public:/proj-cont/public

  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx/Dockerfile
    container_name: rrrp-nginx-cont
    depends_on:
      - web
    image: rrrp-nginx-img
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./tmp/sockets
        target: /proj-cont/tmp/sockets
      - type: bind
        source: ./public
        target: /proj-cont/public

# トップレベルの名前付きボリュームを
# ホストマシン上にマウントする場合
# 
# services: 
#   web:
#     volumes:
#       - sockets:/proj-cont/tmp/sockets
#       - public:/proj-cont/public
#   nginx:
#     volumes:
#       - sockets:/proj-cont/tmp/sockets
#       - public:/proj-cont/public
# volumes:
#   sockets:
#   public:
