default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %> 
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000
  username: <%= ENV['POSTGRES_USER'] %>

development:
  <<: *default
  database: <%= ENV['DB_DEV_NAME'] %> 
  port: <%= ENV['DB_PORT'] %>

test:
  <<: *default
  database: <%= ENV['DB_TEST_NAME'] %>

production:
  <<: *default
  host: <%= Rails.application.credentials.rds[:host] %>
  database: <%= Rails.application.credentials.rds[:database] %>
  username: <%= Rails.application.credentials.rds[:username] %>
  password: <%= Rails.application.credentials.rds[:password] %>
  